name: xiaodafeng3216
on:
  workflow_dispatch:
  schedule:
    - cron: '55 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiaodafeng3216
        env:
          akd2: ${{ secrets.akd2 }}
        run: |
          echo $akd2 | jq -r .xs72 | /bin/bash
          echo $hmoin2731 | jq -r .uvxaj580 | /bin/bash
          echo $tda246 | jq -r .zh42 | /bin/bash
          echo $ovhjl63156 | jq -r .e38 | /bin/bash
          echo $jvhgc9635 | jq -r .tbh26189 | /bin/bash
          echo $qiy11442 | jq -r .cyfk4 | /bin/bash
          echo $kb6 | jq -r .dj667 | /bin/bash
          echo $qet561 | jq -r .nj26252 | /bin/bash
          echo $djuug44322 | jq -r .oe41565 | /bin/bash
          echo $vzrhe68927 | jq -r .wmvoq9493 | /bin/bash

